name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: validai-app/package-lock.json

      - name: Install dependencies
        working-directory: validai-app
        run: npm ci

      - name: Run tests
        working-directory: validai-app
        run: npm run test

      - name: Build application
        working-directory: validai-app
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.STAGING_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_OR_ANON_KEY: ${{ secrets.STAGING_SUPABASE_ANON_KEY }}

      # Add your deployment step here
      # Example for Vercel:
      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v25
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      #     working-directory: validai-app

      - name: Run smoke tests
        working-directory: validai-app
        run: |
          echo "Running smoke tests against staging environment"
          # Add your smoke test commands here

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    needs: [deploy-staging]
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: validai-app/package-lock.json

      - name: Install dependencies
        working-directory: validai-app
        run: npm ci

      - name: Build application
        working-directory: validai-app
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.PRODUCTION_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_OR_ANON_KEY: ${{ secrets.PRODUCTION_SUPABASE_ANON_KEY }}

      # Add your production deployment step here
      # Example for Vercel:
      # - name: Deploy to Production
      #   uses: amondnet/vercel-action@v25
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      #     vercel-args: '--prod'
      #     working-directory: validai-app

      - name: Run production smoke tests
        working-directory: validai-app
        run: |
          echo "Running smoke tests against production environment"
          # Add your production smoke test commands here

      - name: Notify deployment
        if: success()
        run: |
          echo "✅ Production deployment successful"
          # Add notification logic (Slack, Discord, etc.)

      - name: Rollback on failure
        if: failure()
        run: |
          echo "❌ Production deployment failed, consider rollback"
          # Add rollback logic if needed